### ISSUE TITLE
Change custom webhook template format for AlarmID

### ISSUE THREAD

**Issue by dustinbeare** [kentik/custom-notification-templates#11]
Following the Alerting 2.0 changes, can we change the webhook and other templates to reflect that the AlarmID will now be sent as a UUID string field, as it still is formatted for an integer to be sent. Specifically, the json-legacy.tmpl, line 12.

Also, if we could modify the output when testing a new json.tmpl, can we change the AlarmID to reflect the new UUID field, rather than the old 9-digit number? Thanks!

**Comment by remi00** [comment]
Completed with #12
